/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class example_Example */

#ifndef _Included_example_Example
#define _Included_example_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     example_Example
 * Method:    change_table
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_example_Example_change_1table
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
