/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Xreplacer */

#ifndef _Included_Xreplacer
#define _Included_Xreplacer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Xreplacer
 * Method:    change_table
 * Signature: ([Ljava/lang/String;[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Xreplacer_change_1table
  (JNIEnv *, jobject, jobjectArray, jobjectArray, jint);

#ifdef __cplusplus
}
#endif
#endif
